### ISSUE TITLE
Unfortunately URL was changed by TikTok and this does not work anymore

### ISSUE THREAD

**Issue by RotemAkerman** [vionde/TikTok-no-watermark-downloader#1]
`https://api2.musical.ly/aweme/v1/playwm/?video_id` is no longer valid

**Comment by vionde** [comment]
Sorry for long response. Updated

**Comment by oluwabajio** [comment]
This is no longer working.

i used https://api2-16-h2.musical.ly/aweme/v1/play/?video_id=v090447c0000bq8a1cea9rhaargmnlng 

its not working
